---
title: "Draft: Data Documentation"
---


For the exploration of the scenario "London Bridge is Falling Down", the data set consulted will be pulled from the United States Department of Transit's National Bridge Inventory. Not every variable in the data set will be included or transformed into a different variable. The data will pertain only to Douglas County in Nebraska, filtered with the known state and county codes. @NationalBridgeInventory

# National Bridge Inventory Data

| Name | Data Name | Data Type | Range | Description |
|------|-----------|-----------|-------|-------------|
| State Code | STATE_CODE_001 | Integer | 1-72 | Code belonging to which state the bridge belongs to |
| Record Type | RECORD_TYPE_005A | Character | 1-2Z | Designation of what type of record, with 1 referring to traffic that is on the bridge and 2 referring to underneath the bridge with letters depicting different areas |
| County Code | COUNTY_CODE_003 | Integer | 1-185 | 3 digit FIPS code belonging to the county the bridge is located in |
| Year Built | YEAR_BUILT_027 | Integer | 1888-2025 | Integer corresponding to what year the bridge was built |
| Lanes On the Structure | TRAFFIC_LANES_ON_028A | Integer | 1-12 | Number of lanes on the structure |
| Lanes Under the Structure | TRAFFIC_LANES_UND_028B | Integer | 0-17 | Number of lanes under the structure |
| Average Daily Traffic | ADT_029 | Integer | 0-6425 | Number of average daily traffic for the area of |
| Year of Average Daily Traffic | YEAR_ADT_030 | Integer | 1988-2025 | Year recorded corresponding to when the average daily traffic was recorded |
| Structure Open, Posted, or Closed to Traffic | OPEN_CLOSED_POSTED_041 | Character | A-K | Single letter denoting the traffic status of the bridge: A: open, B,D,E: open with stipulations, G: new structure not open yet, K: closed to all traffic, P,R: Posted |
| Is Above a Waterway | IS_ABOVE_WATERWAY | Integer | 0,1 | Determined through the Type of Service variable in the original National Bridge Inventory data set, which are indicated as above a waterway with the codes 5-9 |
| Length of Maximum Span | MAX_SPAN_LEN_MT_048 | Numeric | 0-190.2 | Length in meters of the maximum span of the bridge |
| Structure Length | STRUCTURE_LEN_MT_049 | Numeric | 6.1-1646.5 | Length of the bridge in meters |
| Bridge Roadway Width, Curb-to-Curb | ROADWAY_WIDTH_MT_051 | Numeric | 0-69.7 | Minimum width of the roadway on the bridge from the curb railing, or other restrictive measure, exclusive of flared areas for ramps |
| Deck Width, Out-to-Out | DECK_WIDTH_MT_052 | Numeric | 0-234.1 | Out-to-out width of the bridge in meters, exclusive of flared areas for ramps |
| Minimum Vertical Clearance Over Bridge Roadway | VERT_CLR_OVER_MT_053 | Numeric | 3.96-99.99 | Minimum vertical clearance in meters over the bridge roadway, including shoulders, to any superstructure restriction |
| Deck Condition Rating | DECK_COND_058 | Character | N, 0-9 | Condition of the deck of the bridge on a scale of 0-9 with 0 being failed condition and 9 being excellent condition |
| Superstructure Condition Rating | SUPERSTRUCTURE_COND_059 | Character | N, 0-9 | Condition of the superstructure of the bridge on a scale of 0-9 with 0 being failed condition and 9 being excellent condition |
| Substructure Condition Rating | SUBSTRUCTURE_COND_060 | Character | N, 0-9 | Condition of the substructure of the bridge on a scale of 0-9 with 0 being failed condition and 9 being excellent condition |
| Longitude | LONGDD | Numeric | -174.1823-0 | Latitudinal coordinate of where the bridge is located |
| Latitude | LATDD | Numeric | 0-70.21645 | Longitudinal coordinate of where the bridge is located |